# Generated by Django 3.1.1 on 2020-10-20 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=100)),
                ('assignment_description', models.CharField(max_length=100)),
                ('college', models.CharField(choices=[('AMITY', 'Amity'), ('NMIMS', 'Nmims')], max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('assignment_file', models.FileField(upload_to='general_assignments/')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField()),
                ('subject_name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('special_mention', models.CharField(max_length=500)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('receipt', models.CharField(max_length=50)),
                ('orderid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
