# Generated by Django 3.1 on 2020-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20201001_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='orderid',
            field=models.CharField(max_length=100),
        ),
    ]
